import { StyleSheet } from 'react-native';

// Global colour palette (deep purple + gold, yantra aesthetic).
// Referenced from every screen — do not hard-code hex codes elsewhere.
const C = {
  bg:'#1a0a2e', bgCard:'#2a1040', bgDeep:'#2a0a4a',
  border:'#4a2a6a', borderFaint:'#3d2a5a',
  gold:'#c9a96e', goldLight:'#e8d5a3',
  muted:'#8a6a9a', faint:'#6a4a7a', fainter:'#5a3a7a',
  purple:'#3d1a60', purpleBorder:'#6a3a8a',
  green:'#6ae0a0', greenBg:'#0a2a1a', greenBorder:'#2a6a4a',
  red:'#e06060', redBg:'#2a0a0a', redBorder:'#6a2a2a',
  blue:'#6ab0e0', blueBg:'#1a2a4a',
  orange:'#e09060', orangeBg:'#3a1a0a',
};

// Header styles.
const hd = StyleSheet.create({
  header:    { flexDirection:'column', alignItems:'center', backgroundColor:C.bgDeep, paddingHorizontal:16, paddingVertical:14, borderBottomWidth:0.5, borderColor:C.borderFaint },
  om:        { fontSize:36, color:C.gold },
  logo:      { width:44, height:44 },
  logoHeader:{ width:280, height:58, marginBottom:6 },
  headerRow: { flexDirection:'row', alignItems:'center', justifyContent:'space-between', width:'100%', paddingHorizontal:8 },
  center:    { flex:1 },
  title:     { fontSize:22, fontWeight:'500', color:C.goldLight, letterSpacing:0.8 },
  subtitle:  { fontSize:13, color:C.muted },
  timeLabel: { fontSize:18, color:C.gold, fontWeight:'500' },
  sunBig:    { flexDirection:'row', alignItems:'center', justifyContent:'space-around', backgroundColor:C.bgDeep, paddingVertical:10, paddingHorizontal:20, borderBottomWidth:0.5, borderColor:C.borderFaint },
  sunItem:   { flex:1, alignItems:'center' },
  sunRow:    { flexDirection:'row', alignItems:'center', gap:10 },
  sunTextCol:{ alignItems:'flex-end' },
  sunImg:    { width:42, height:42 },
  sunDivider:{ width:0.5, height:34, backgroundColor:C.borderFaint },
  sunIcon:   { fontSize:20, marginBottom:2 },
  sunTime:   { fontSize:18, fontWeight:'500', color:C.goldLight, letterSpacing:0.5 },
  sunLabelBig:{ fontSize:9, color:C.muted, marginTop:1, textTransform:'uppercase', letterSpacing:1 },
  srcLabel:  { fontSize:11, color:C.faint, textAlign:'center', paddingVertical:6, backgroundColor:C.bgDeep, borderBottomWidth:0.5, borderColor:C.borderFaint },
});


// Tattva Detail card (used on Home).
const td = StyleSheet.create({
  card:     { marginHorizontal:16, marginBottom:12, backgroundColor:C.bgCard, borderRadius:14, borderWidth:1, padding:16 },
  topRow:   { flexDirection:'row', alignItems:'center', gap:12, marginBottom:12 },
  colorDot: { width:16, height:16, borderRadius:8 },
  iconImg:  { width:48, height:48, marginRight:4 },
  name:     { fontSize:19, fontWeight:'500', color:C.goldLight },
  chakra:   { fontSize:13, color:C.muted, marginTop:3 },
  symbolBox:{ backgroundColor:'#2a1040', borderRadius:8, padding:8 },
  symbol:   { fontSize:14, fontWeight:'500' },
  divider:  { height:0.5, backgroundColor:C.border, marginBottom:12 },
  infoRow:  { flexDirection:'row' },
  infoItem: { alignItems:'center', flex:1 },
  infoLabel:{ fontSize:11, color:C.muted, textTransform:'uppercase', letterSpacing:0.8, marginBottom:4 },
  infoVal:  { fontSize:14, fontWeight:'500' },
  desc:     { fontSize:14, color:'#a08ab0', lineHeight:22, marginTop:12 },
});


// Global shared styles.
const s = StyleSheet.create({
  svaraCard:    { margin:16, marginBottom:12, backgroundColor:C.bgCard, borderRadius:16, borderWidth:1, borderColor:C.gold, paddingVertical:20, paddingHorizontal:16, alignItems:'center' },
  svaraIconImg: { width:72, height:72, marginBottom:8 },
  nextNadiText: { fontSize:13, color:C.muted, marginTop:12, textAlign:'center' },
  svaraLabel:   { fontSize:12, color:C.muted, textTransform:'uppercase', letterSpacing:1.2, marginBottom:8 },
  svaraName:    { fontSize:28, fontWeight:'500', color:C.gold, letterSpacing:0.5 },
  badge:        { marginTop:10, paddingVertical:6, paddingHorizontal:16, borderRadius:20, backgroundColor:C.purple, borderWidth:0.5, borderColor:C.purpleBorder },
  badgeText:    { fontSize:13, color:C.gold },
  compareCard:  { marginHorizontal:16, marginBottom:12, backgroundColor:C.bgCard, borderRadius:12, borderWidth:0.5, borderColor:C.border, paddingVertical:12, paddingHorizontal:14, flexDirection:'row', alignItems:'center', justifyContent:'space-between' },
  compareItem:  { flex:1, alignItems:'center' },
  compareLabel: { fontSize:11, color:C.muted, textTransform:'uppercase', letterSpacing:0.8, marginBottom:4 },
  compareValue: { fontSize:14, fontWeight:'500', color:C.goldLight },
  compareArrow: { fontSize:12, color:C.faint, marginHorizontal:8, fontStyle:'italic' },
  moodCard:     { marginHorizontal:16, marginBottom:8, paddingVertical:12, paddingHorizontal:14, backgroundColor:C.purple, borderRadius:12, borderWidth:0.5, borderColor:C.gold, alignItems:'center' },
  moodLabel:    { fontSize:11, color:C.muted, textTransform:'uppercase', letterSpacing:1, marginBottom:4 },
  moodText:     { fontSize:15, color:C.gold, fontWeight:'500', textAlign:'center', fontStyle:'italic' },
  tattvaRow:    { flexDirection:'row', marginHorizontal:16, marginBottom:12, gap:6 },
  tattvaPill:   { flex:1, backgroundColor:C.bgCard, borderWidth:0.5, borderColor:C.border, borderRadius:12, paddingVertical:14, alignItems:'center' },
  tattvaPillActive:{ backgroundColor:C.purple, borderColor:C.gold },
  tattvaIcon:   { fontSize:22, marginBottom:3 },
  tattvaIconImg:{ width:34, height:34, marginBottom:3 },
  tattvaName:   { fontSize:12, color:C.muted },
  ddRow:        { flexDirection:'row', marginHorizontal:16, marginBottom:16, gap:8 },
  ddBox:        { flex:1, borderRadius:14, padding:14, borderWidth:0.5 },
  ddHeader:     { fontSize:13, fontWeight:'500', textTransform:'uppercase', letterSpacing:1, marginBottom:10 },
  ddItem:       { flexDirection:'row', alignItems:'flex-start', gap:6, marginBottom:7 },
  ddDot:        { width:5, height:5, borderRadius:2.5, marginTop:6 },
  ddText:       { fontSize:13, lineHeight:18, flex:1 },
  verseCard:    { marginHorizontal:16, marginBottom:14, backgroundColor:C.bgCard, borderRadius:14, borderWidth:0.5, borderColor:C.border, padding:14 },
  verseLabel:   { fontSize:12, color:C.muted, textTransform:'uppercase', letterSpacing:1, marginBottom:8 },
  verseText:    { fontSize:15, color:C.gold, lineHeight:24, fontStyle:'italic' },
  verseRef:     { fontSize:12, color:C.faint, marginTop:8 },
  screenHeader: { backgroundColor:C.bgDeep, paddingTop:24, paddingBottom:18, paddingHorizontal:20, borderBottomWidth:0.5, borderColor:C.borderFaint },
  screenTitle:  { fontSize:22, fontWeight:'500', color:C.goldLight },
  screenDesc:   { fontSize:14, color:C.muted, marginTop:4 },
  card:         { margin:14, backgroundColor:C.bgCard, borderRadius:14, borderWidth:0.5, borderColor:C.border, padding:16 },
  step:         { fontSize:15, color:'#a08ab0', marginBottom:12, lineHeight:24 },
  btnRow:       { flexDirection:'row', marginHorizontal:14, gap:8 },
  svaraBtn:     { flex:1, backgroundColor:C.bgCard, borderWidth:0.5, borderColor:C.border, borderRadius:14, paddingVertical:18, alignItems:'center', gap:6 },
  svaraBtnActive:{ backgroundColor:C.purple, borderColor:C.gold },
  svaraBtnIcon: { fontSize:30 },
  svaraBtnIconImg: { width:48, height:48, marginBottom:4 },
  svaraBtnLabel:{ fontSize:14, color:C.muted },
  resultBox:    { margin:14, backgroundColor:C.purple, borderRadius:14, borderWidth:0.5, borderColor:C.gold, padding:16 },
  resultTitle:  { fontSize:16, color:C.gold, fontWeight:'500', marginBottom:8 },
  resultBody:   { fontSize:14, color:'#a08ab0', lineHeight:22 },
  dayCell:      { width:42, height:42, borderRadius:8, alignItems:'center', justifyContent:'center', borderWidth:0.5 },
  shlokaCard:   { backgroundColor:C.bgCard, borderWidth:0.5, borderColor:C.border, borderRadius:14, padding:16, marginBottom:12 },
  lunarDayCard: { marginHorizontal:16, marginBottom:10, backgroundColor:C.bgCard, borderRadius:14, borderWidth:1, padding:14 },
  lunarDayHeader:{ marginBottom:8 },
  lunarDayLabel:{ fontSize:11, color:C.muted, textTransform:'uppercase', letterSpacing:1, marginBottom:4 },
  lunarDayTitle:{ fontSize:17, color:C.gold, fontWeight:'500', marginBottom:3 },
  lunarDayMeaning:{ fontSize:13, fontStyle:'italic' },
  lunarDayNadi: { backgroundColor:C.bg, borderRadius:8, padding:8, marginTop:4 },
  lunarDDBox:   { flex:1, borderRadius:10, padding:10, borderWidth:0.5 },
  sectionLabel: { fontSize:13, color:C.faint, textTransform:'uppercase', letterSpacing:1.5 },
  settingCard:  { backgroundColor:C.bgCard, borderRadius:14, borderWidth:0.5, borderColor:C.border, overflow:'hidden' },
  settingRow:   { flexDirection:'row', alignItems:'center', justifyContent:'space-between', padding:14, paddingHorizontal:16, borderBottomWidth:0.5, borderColor:'#3a1a5a' },
  settingTitle: { fontSize:15, color:C.goldLight },
  settingSub:   { fontSize:12, color:C.muted, marginTop:3 },
  saveBtn:      { alignItems:'center', justifyContent:'center', backgroundColor:C.purple, borderWidth:0.5, borderColor:C.gold, borderRadius:14, padding:16 },
  trialBanner:  { backgroundColor:'#2a1040', paddingVertical:8, paddingHorizontal:14, borderBottomWidth:0.5, borderColor:C.gold },
  trialText:    { fontSize:12, color:C.goldLight, textAlign:'center', letterSpacing:0.4 },
  freeHomeCenter:{ paddingVertical:24, paddingHorizontal:16, alignItems:'center', gap:14 },
  freeCard:     { width:'100%', backgroundColor:C.bgCard, borderRadius:16, borderWidth:1, borderColor:C.border, paddingVertical:24, paddingHorizontal:16, alignItems:'center' },
  freeLabel:    { fontSize:11, color:C.muted, textTransform:'uppercase', letterSpacing:1.2, marginBottom:10 },
  freeName:     { fontSize:24, fontWeight:'500', color:C.goldLight, letterSpacing:0.5, marginTop:6 },
  freeHint:     { fontSize:12, color:C.muted, textAlign:'center', lineHeight:18, paddingHorizontal:14, marginTop:6, fontStyle:'italic' },
  bottomNav:    { flexDirection:'row', backgroundColor:C.bg, borderTopWidth:0.5, borderColor:C.borderFaint, paddingTop:10 },
  navItem:      { flex:1, alignItems:'center', gap:4 },
  navIcon:      { fontSize:26 },
  navIconImg:   { width:28, height:28 },
  navLabel:     { fontSize:11, color:C.fainter },
});


// Timeline row styles.
const tl = StyleSheet.create({
  row:        { flexDirection:'row', alignItems:'center', backgroundColor:C.bgCard, borderRadius:12, padding:12, marginBottom:8, borderWidth:0.5, borderColor:C.borderFaint },
  rowNow:     { borderColor:C.gold, borderWidth:1.5, backgroundColor:C.purple },
  timeCol:    { width:78 },
  time:       { fontSize:16, color:C.goldLight, fontWeight:'500' },
  until:      { fontSize:11, color:C.faint, marginTop:2 },
  dot:        { width:12, height:12, borderRadius:6, marginHorizontal:12 },
  icon:       { width:40, height:40, marginHorizontal:10 },
  tattvaCol:  { flex:1 },
  tattvaName: { fontSize:16, color:C.goldLight, fontWeight:'500' },
  tattvaDesc: { fontSize:12, color:'#a08ab0', lineHeight:17, marginTop:4 },
});


// Sub-screen (Settings) styles.
const ss = StyleSheet.create({
  modeBtn:      { flex:1, padding:12, borderRadius:8, backgroundColor:C.bgCard, borderWidth:0.5, borderColor:C.border, alignItems:'center' },
  modeBtnActive:{ backgroundColor:C.purple, borderColor:C.gold },
  modeBtnText:  { fontSize:13, color:C.muted },
  modeCard:     { backgroundColor:C.bgCard, borderRadius:14, borderWidth:0.5, borderColor:C.border, padding:14 },
  modeCardActive:{ borderColor:C.gold, borderWidth:1, backgroundColor:C.purple },
  modeCardIcon: { fontSize:22, marginRight:10 },
  modeCardTitle:{ fontSize:15, color:C.goldLight, fontWeight:'500' },
  modeCardSub:  { fontSize:12, color:C.muted, marginTop:3, lineHeight:17 },
  modeRadio:    { width:18, height:18, borderRadius:9, borderWidth:1.5, borderColor:C.muted, marginRight:10, alignItems:'center', justifyContent:'center' },
  modeRadioActive:{ borderColor:C.gold },
  modeRadioInner:{ width:8, height:8, borderRadius:4, backgroundColor:C.gold },
  modeCardBody: { marginTop:12, paddingTop:12, borderTopWidth:0.5, borderColor:'#3a1a5a' },
  modeStatus:   { fontSize:14, color:C.goldLight, fontWeight:'500' },
  modeCoords:   { fontSize:12, color:C.muted, marginTop:2 },
  modeBtnInline:{ backgroundColor:C.bg, borderWidth:0.5, borderColor:C.gold, borderRadius:10, paddingVertical:10, alignItems:'center' },
  manualRow:    { flexDirection:'row', alignItems:'center', justifyContent:'space-between', paddingVertical:8 },
  manualLabel:  { fontSize:14, color:C.goldLight, flex:1 },
  tabRow:       { flexDirection:'row', backgroundColor:'#1f0830', borderTopLeftRadius:14, borderTopRightRadius:14 },
  tabBtn:       { flex:1, paddingVertical:14, alignItems:'center', borderBottomWidth:2, borderColor:'transparent' },
  tabBtnActive: { borderColor:C.gold, backgroundColor:C.purple },
  tabBtnText:   { fontSize:14, color:C.muted, fontWeight:'500' },
  tabBody:      { padding:14 },
  useCalcRow:   { flexDirection:'row', alignItems:'center', padding:12, paddingHorizontal:16, borderTopWidth:0.5, borderBottomWidth:0.5, borderColor:'#3a1a5a', gap:10 },
  useCalcBtn:   { paddingVertical:6, paddingHorizontal:12, borderRadius:8, backgroundColor:C.purple, borderWidth:0.5, borderColor:C.gold },
  inputRow:     { flexDirection:'row', alignItems:'center', justifyContent:'space-between', padding:14, paddingHorizontal:16, borderBottomWidth:0.5, borderColor:'#3a1a5a' },
  input:        { backgroundColor:C.bg, borderWidth:0.5, borderColor:C.border, borderRadius:8, color:C.gold, fontSize:15, paddingVertical:8, paddingHorizontal:12, minWidth:100, textAlign:'right' },
  timeRow:      { flexDirection:'row', alignItems:'center', gap:4 },
  timePart:     { width:48, textAlign:'center', minWidth:48 },
});

export { C, hd, td, s, tl, ss };
